name = "WeaklySeparatedCollections"
uuid = "1ef1bab6-26f5-49e7-acb3-59355e138888"
authors = ["Michael Schlößer"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
